name: server
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  socket_io: ^0.9.4
  meta: ^1.3.0
  common:
    path: ../common

  socket_io_common: ^0.9.0+5
  
dev_dependencies:
  pedantic: ^1.9.0
 
